package com.dasha.equipment.command;

/**
 * Created by Даша on 12.01.2017.
 */
public enum CommandName {
    ADD_EQUIPMENT,DELETE_EQUIPMENT,GET_AVAILABLE_EQUIPMENT,
    GET_EQUIPMENT_BY_CATEGORY_ID,GET_EQUIPMENT_BY_TITLE,
    ADD_CATEGORY,DELETE_CATEGORY,GET_ALL_CATEGORIES,
    DELETE_USER,ADD_USER,
    RENT_UNIT,CONFIRM_RETURN,GET_RENTED_UNITS,
    WRONG_REQUEST
}
